spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/twt_base
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: false
      format_sql: false
    #     open-in-view: false
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

  thymeleaf:
    check-template-location: false

  mail:
    host: smtp.gmail.com
    username: perfumestoreapp@gmail.com
    password: oggmtuvzwyxbvifk
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

google:
  api:
    url: https://www.googleapis.com/youtube/v3/videos?id=%s&key=%s&part=snippet,contentDetails,statistics,status
    key: AIzaSyAyhB6MnJNlOGXJkibk-07VgGSxmn72-vU

jwt:
  header: Authorization
  secret: dejavudejavudejavudejavudejavudejavudejavudejavudejavudejavu
  expiration: 6048000

amazon:
  aws:
    access-key: AKIA2GKIUFNQ24L7PXBB
    secret-key: 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
  s3:
    bucket:
      name: perfumeshop

hostname: localhost:3000

mail:
  debug: false