CREATE TABLE chats_participants
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    left_chat BOOLEAN DEFAULT FALSE,
    chat_id   BIGINT,
    user_id   BIGINT,
    CONSTRAINT chats_participants_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    about                 VARCHAR(255),
    activation_code       VARCHAR(255),
    active                BOOLEAN DEFAULT FALSE,
    background_color      VARCHAR(255),
    birthday              VARCHAR(255),
    color_scheme          VARCHAR(255),
    country               VARCHAR(255),
    country_code          VARCHAR(255),
    email                 VARCHAR(255),
    full_name             VARCHAR(255),
    gender                VARCHAR(255),
    language              VARCHAR(255),
    like_count            INTEGER DEFAULT 0,
    location              VARCHAR(255),
    media_tweet_count     INTEGER DEFAULT 0,
    muted_direct_messages BOOLEAN DEFAULT FALSE,
    notifications_count   INTEGER DEFAULT 0,
    password              VARCHAR(255),
    password_reset_code   VARCHAR(255),
    phone                 BIGINT,
    private_profile       BOOLEAN DEFAULT FALSE,
    profile_customized    BOOLEAN DEFAULT FALSE,
    profile_started       BOOLEAN DEFAULT FALSE,
    registration_date     TIMESTAMP WITHOUT TIME ZONE,
    role                  VARCHAR(255),
    tweet_count           INTEGER DEFAULT 0,
    username              VARCHAR(255),
    website               VARCHAR(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE users_notifications
(
    user_id          BIGINT NOT NULL,
    notifications_id BIGINT NOT NULL
);

CREATE TABLE pools_poll_choices
(
    poll_id         BIGINT NOT NULL,
    poll_choices_id BIGINT NOT NULL
);

CREATE TABLE users_bookmarks
(
    user_id      BIGINT NOT NULL,
    bookmarks_id BIGINT NOT NULL
);

CREATE TABLE tweets_images
(
    tweet_id  BIGINT NOT NULL,
    images_id BIGINT NOT NULL
);

ALTER TABLE users_notifications
    ADD CONSTRAINT uk_fqai0p0e0nsyh9pp2j0h32ggq UNIQUE (notifications_id);

ALTER TABLE pools_poll_choices
    ADD CONSTRAINT uk_l2rmjmwo83tkbv42fipfqh30y UNIQUE (poll_choices_id);

ALTER TABLE users_bookmarks
    ADD CONSTRAINT uk_loov487ifqjjlvuj0a9s4g4ta UNIQUE (bookmarks_id);

ALTER TABLE tweets_images
    ADD CONSTRAINT uk_r0mdr0mxkjw13pm37pqs86vl UNIQUE (images_id);

CREATE TABLE bookmarks
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bookmark_date TIMESTAMP WITHOUT TIME ZONE,
    tweet_id      BIGINT,
    users_id      BIGINT,
    CONSTRAINT bookmarks_pkey PRIMARY KEY (id)
);

CREATE TABLE chat_messages
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date     TIMESTAMP WITHOUT TIME ZONE,
    text     VARCHAR(255),
    user_id  BIGINT,
    chat_id  BIGINT,
    tweet_id BIGINT,
    CONSTRAINT chat_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE chat_to_user
(
    chat_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE TABLE chats
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT chats_pkey PRIMARY KEY (id)
);

CREATE TABLE images
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    src VARCHAR(255),
    CONSTRAINT images_pkey PRIMARY KEY (id)
);

CREATE TABLE like_tweets
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    like_tweet_date TIMESTAMP WITHOUT TIME ZONE,
    tweets_id       BIGINT,
    users_id        BIGINT,
    CONSTRAINT like_tweets_pkey PRIMARY KEY (id)
);

CREATE TABLE lists
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    alt_wallpaper VARCHAR(255),
    description   VARCHAR(255),
    private       BOOLEAN,
    name          VARCHAR(255),
    pinned_date   TIMESTAMP WITHOUT TIME ZONE,
    user_id       BIGINT,
    wallpaper_id  BIGINT,
    CONSTRAINT lists_pkey PRIMARY KEY (id)
);

CREATE TABLE lists_followers
(
    lists_id     BIGINT NOT NULL,
    followers_id BIGINT NOT NULL
);

CREATE TABLE lists_members
(
    lists_id   BIGINT NOT NULL,
    members_id BIGINT NOT NULL
);

CREATE TABLE lists_tweets
(
    lists_id  BIGINT NOT NULL,
    tweets_id BIGINT NOT NULL
);

CREATE TABLE notifications
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date              TIMESTAMP WITHOUT TIME ZONE,
    notification_type VARCHAR(255),
    tweet_id          BIGINT,
    user_id           BIGINT,
    user_to_follow_id BIGINT,
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE pool_choices
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    choice VARCHAR(255),
    CONSTRAINT pool_choices_pkey PRIMARY KEY (id)
);

CREATE TABLE pool_choices_voted_user
(
    poll_choice_id BIGINT NOT NULL,
    voted_user_id  BIGINT NOT NULL
);

CREATE TABLE pools
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pools_pkey PRIMARY KEY (id)
);

CREATE TABLE replies
(
    tweets_id BIGINT NOT NULL,
    reply_id  BIGINT NOT NULL
);

CREATE TABLE retweets
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    retweet_date TIMESTAMP WITHOUT TIME ZONE,
    tweets_id    BIGINT,
    users_id     BIGINT,
    CONSTRAINT retweets_pkey PRIMARY KEY (id)
);

CREATE TABLE subscribers
(
    user_id       BIGINT NOT NULL,
    subscriber_id BIGINT NOT NULL
);

CREATE TABLE tags
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tag_name        VARCHAR(255),
    tweets_quantity BIGINT,
    CONSTRAINT tags_pkey PRIMARY KEY (id)
);

CREATE TABLE tweet_pool
(
    pools_id  BIGINT,
    tweets_id BIGINT NOT NULL,
    CONSTRAINT tweet_pool_pkey PRIMARY KEY (tweets_id)
);

CREATE TABLE tweet_quote
(
    quote_tweet_id BIGINT,
    tweets_id      BIGINT NOT NULL,
    CONSTRAINT tweet_quote_pkey PRIMARY KEY (tweets_id)
);

CREATE TABLE tweets
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    addressed_id       BIGINT,
    addressed_tweet_id BIGINT,
    addressed_username VARCHAR(255),
    date_time          TIMESTAMP WITHOUT TIME ZONE,
    link               VARCHAR(255),
    link_cover         VARCHAR(255),
    link_cover_size    VARCHAR(255),
    link_description   VARCHAR(255),
    link_title         VARCHAR(255),
    reply_type         VARCHAR(255),
    scheduled_date     TIMESTAMP WITHOUT TIME ZONE,
    text               TEXT,
    users_id           BIGINT,
    CONSTRAINT tweets_pkey PRIMARY KEY (id)
);

CREATE TABLE tweets_tags
(
    tags_id   BIGINT NOT NULL,
    tweets_id BIGINT NOT NULL
);

CREATE TABLE unread_messages
(
    user_id         BIGINT NOT NULL,
    chat_message_id BIGINT NOT NULL
);

CREATE TABLE user_avatar
(
    avatar_id BIGINT,
    user_id   BIGINT NOT NULL,
    CONSTRAINT user_avatar_pkey PRIMARY KEY (user_id)
);

CREATE TABLE user_blocked
(
    user_id         BIGINT NOT NULL,
    blocked_user_id BIGINT NOT NULL
);

CREATE TABLE user_follower_requests
(
    user_id     BIGINT NOT NULL,
    follower_id BIGINT NOT NULL
);

CREATE TABLE user_muted
(
    user_id       BIGINT NOT NULL,
    muted_user_id BIGINT NOT NULL
);

CREATE TABLE user_pinned_tweet
(
    tweet_id BIGINT,
    user_id  BIGINT NOT NULL,
    CONSTRAINT user_pinned_tweet_pkey PRIMARY KEY (user_id)
);

CREATE TABLE user_subscriptions
(
    subscriber_id BIGINT NOT NULL,
    user_id       BIGINT NOT NULL
);

CREATE TABLE user_wallpaper
(
    wallpaper_id BIGINT,
    user_id      BIGINT NOT NULL,
    CONSTRAINT user_wallpaper_pkey PRIMARY KEY (user_id)
);

CREATE TABLE users_tweets
(
    user_id   BIGINT NOT NULL,
    tweets_id BIGINT NOT NULL
);

CREATE TABLE users_user_lists
(
    user_id       BIGINT NOT NULL,
    user_lists_id BIGINT NOT NULL
);

ALTER TABLE users_notifications
    ADD CONSTRAINT fk17pt2krtfgoof65xdvtbpf5aw FOREIGN KEY (notifications_id) REFERENCES notifications (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE replies
    ADD CONSTRAINT fk1og4qeuvwr4yt0py1yq2jk794 FOREIGN KEY (tweets_id) REFERENCES tweets (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE like_tweets
    ADD CONSTRAINT fk1qkohfdrx5cta7p8y8f4o32nv FOREIGN KEY (users_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tweets_tags
    ADD CONSTRAINT fk1tgno5q3spbt9k8nc9jor8xnu FOREIGN KEY (tweets_id) REFERENCES tweets (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_blocked
    ADD CONSTRAINT fk1wp478xhxe2jjsagyb0vnrixm FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE lists_members
    ADD CONSTRAINT fk2jagg2qq4hgojny4m0vab1a41 FOREIGN KEY (lists_id) REFERENCES lists (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tweet_quote
    ADD CONSTRAINT fk3an4vbda2c9lw7gla5tng2um4 FOREIGN KEY (tweets_id) REFERENCES tweets (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE lists_members
    ADD CONSTRAINT fk3eyxgv67fr9v8v1hoyuntj499 FOREIGN KEY (members_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_blocked
    ADD CONSTRAINT fk3ft7jt92le6bivrrwj25f87i9 FOREIGN KEY (blocked_user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_subscriptions
    ADD CONSTRAINT fk3l40lbyji8kj5xoc20ycwsc8g FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_subscriptions
    ADD CONSTRAINT fk6dh0jqt57w1molih5xjhb8nd0 FOREIGN KEY (subscriber_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE chat_messages
    ADD CONSTRAINT fk6f0y4l43ihmgfswkgy9yrtjkh FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE like_tweets
    ADD CONSTRAINT fk6hb4ee6u0e9ljyp7gp1utqqcq FOREIGN KEY (tweets_id) REFERENCES tweets (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tweets_tags
    ADD CONSTRAINT fk6kghpwtue5ty6ac1mu15bxogh FOREIGN KEY (tags_id) REFERENCES tags (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE lists
    ADD CONSTRAINT fk768jm1btcmvyih0w5ry4yjo7a FOREIGN KEY (wallpaper_id) REFERENCES images (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE users_tweets
    ADD CONSTRAINT fk7v5uijppxedcnbbknqyl7unqq FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE bookmarks
    ADD CONSTRAINT fk85o30yuaayc2kofhc3kljt5wc FOREIGN KEY (tweet_id) REFERENCES tweets (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE bookmarks
    ADD CONSTRAINT fk8xot3y0nq4q3aa476cai9q93d FOREIGN KEY (users_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE pools_poll_choices
    ADD CONSTRAINT fkaqrysc0redvxxcq6s1s13bp2b FOREIGN KEY (poll_choices_id) REFERENCES pool_choices (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE pool_choices_voted_user
    ADD CONSTRAINT fkcr0cypmwnffwhb8uob3s5phym FOREIGN KEY (voted_user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE retweets
    ADD CONSTRAINT fkdhta73liq2531r0u670a0ea73 FOREIGN KEY (tweets_id) REFERENCES tweets (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_muted
    ADD CONSTRAINT fke0j9buuo6ht4pphao101ne08e FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE lists
    ADD CONSTRAINT fke59kv852m4k3g8kmefph4i3kx FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE lists_tweets
    ADD CONSTRAINT fkekr4n4mx3h0wfjoqabkwvb2yh FOREIGN KEY (lists_id) REFERENCES lists (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE users_tweets
    ADD CONSTRAINT fkerekrgspn5at6l8sb5jg2m9ol FOREIGN KEY (tweets_id) REFERENCES tweets (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tweet_pool
    ADD CONSTRAINT fkfd0dxawayvyp132ntdhi8ptfa FOREIGN KEY (pools_id) REFERENCES pools (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tweets
    ADD CONSTRAINT fkfiem2tfp0dq1xsgsax6ju8pa8 FOREIGN KEY (users_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE replies
    ADD CONSTRAINT fkftas7wbrv961d6th8yy5nqdq7 FOREIGN KEY (reply_id) REFERENCES tweets (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tweet_quote
    ADD CONSTRAINT fkftie7ivytjuvpm6118d05upa7 FOREIGN KEY (quote_tweet_id) REFERENCES tweets (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE pools_poll_choices
    ADD CONSTRAINT fkfw9hxy44hoab6qcfth1c50x8i FOREIGN KEY (poll_id) REFERENCES pools (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tweet_pool
    ADD CONSTRAINT fkgia483b845hgruqemh2skyy2v FOREIGN KEY (tweets_id) REFERENCES tweets (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tweets_images
    ADD CONSTRAINT fkgka7vl35am9mwo21xiy4o3dw3 FOREIGN KEY (tweet_id) REFERENCES tweets (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE subscribers
    ADD CONSTRAINT fkh0b65sm1qah4q8iy69k8aaxij FOREIGN KEY (subscriber_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE unread_messages
    ADD CONSTRAINT fkh84h4eq2rt6ams9mbbb0keadp FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE chats_participants
    ADD CONSTRAINT fkhj23i3pyecs1n258gfhcxg74y FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE unread_messages
    ADD CONSTRAINT fkhvny6bgm4d8lv0yhk2c5r9bl8 FOREIGN KEY (chat_message_id) REFERENCES chat_messages (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE users_user_lists
    ADD CONSTRAINT fkhwgg5nh7f35rbflc4il23b6vg FOREIGN KEY (user_lists_id) REFERENCES lists (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE retweets
    ADD CONSTRAINT fkij375t6rmy7uvvc7kb0cl233d FOREIGN KEY (users_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE users_notifications
    ADD CONSTRAINT fkil3tssmpyic5ruavb9jbbw2bb FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_wallpaper
    ADD CONSTRAINT fkj5r6vfnl1ng92trfw95nuj8ck FOREIGN KEY (wallpaper_id) REFERENCES images (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_follower_requests
    ADD CONSTRAINT fkjnjcgbpbaxgnu81g9mardqve9 FOREIGN KEY (follower_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE chats_participants
    ADD CONSTRAINT fkjrfpltus8r643670taov8pana FOREIGN KEY (chat_id) REFERENCES chats (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE lists_tweets
    ADD CONSTRAINT fkki3q16adfmnrsxq5gtkjigeuk FOREIGN KEY (tweets_id) REFERENCES tweets (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE notifications
    ADD CONSTRAINT fkkm4kxtpw8ab56e3v6tuy0pebo FOREIGN KEY (user_to_follow_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_wallpaper
    ADD CONSTRAINT fkl6rrb8qu4wyp9g6eyd1gqs2c6 FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_avatar
    ADD CONSTRAINT fklatwcvwggmxieyymk3e3aah09 FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_follower_requests
    ADD CONSTRAINT fkld8j4caa828qwhp4ca3rf4732 FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE subscribers
    ADD CONSTRAINT fkll9lhik8xj3ep6ahtdt7me7pu FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_muted
    ADD CONSTRAINT fkmfbgdwng6x29fotlaeeo5sdfq FOREIGN KEY (muted_user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tweets_images
    ADD CONSTRAINT fkn08la7vf9dnjm23ddlupi7hjo FOREIGN KEY (images_id) REFERENCES images (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE pool_choices_voted_user
    ADD CONSTRAINT fko4sv895ipikev3ups6nbvk5aq FOREIGN KEY (poll_choice_id) REFERENCES pool_choices (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE lists_followers
    ADD CONSTRAINT fkoncv8qbxpkfdj5261mhoritlw FOREIGN KEY (followers_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_pinned_tweet
    ADD CONSTRAINT fkoyalrx1wxyfmhmnkixxxemcy2 FOREIGN KEY (tweet_id) REFERENCES tweets (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_avatar
    ADD CONSTRAINT fkpcws10nq0scpwil3ubjsjlkya FOREIGN KEY (avatar_id) REFERENCES images (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_pinned_tweet
    ADD CONSTRAINT fkphsi8xxot1g5oqtfghnxi7kih FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE chat_messages
    ADD CONSTRAINT fkpmkrx4gyp9tnhwcsyst5y0cqb FOREIGN KEY (tweet_id) REFERENCES tweets (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE notifications
    ADD CONSTRAINT fkq7of7il7xw8qn87ermsd51gv1 FOREIGN KEY (tweet_id) REFERENCES tweets (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE lists_followers
    ADD CONSTRAINT fkqhwa4ls14obxpwodux07eqoie FOREIGN KEY (lists_id) REFERENCES lists (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE users_user_lists
    ADD CONSTRAINT fkqx4gug6l00hfjayjlgod014cb FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE chat_messages
    ADD CONSTRAINT fkt56nsqjwt7t4sian6vts9wg3t FOREIGN KEY (chat_id) REFERENCES chats (id) ON UPDATE NO ACTION ON DELETE NO ACTION;