db:
  username: test
  password: test

spring:
  datasource:
    username: test
    password: test
  jpa:
    properties.hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:sql-test/clear-chat-db.sql, classpath:sql-test/populate-chat-db.sql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
