server:
  port: 8019

spring:
  application:
    name: email-service
  zipkin:
    base-url: http://localhost:9411
  mail:
    host: smtp.gmail.com
    username: perfumestoreapp@gmail.com
    password: oggmtuvzwyxbvifk
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mail:
  debug: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
