server:
  port: 8021

spring:
  application:
    name: image-service
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411

amazon:
  aws:
    access-key: AKIA2GKIUFNQ24L7PXBB
    secret-key: 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
  s3:
    bucket:
      name: perfumeshop

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${EUREKA_HOST:localhost}
