server:
  port: 8005
spring:
  application:
    name: lists-service
  devtools:
    livereload:
      port: 35739
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/lists
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: false
      format_sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false
  flyway:
    locations: classpath:db/migration/lists
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411
  rabbitmq:
    addresses: ${RABBITMQ_HOST:localhost}:5672

resilience4j:
  circuitbreaker:
    instances:
      notification-service:
        minimum-number-of-calls: 5
      tweet-service:
        minimum-number-of-calls: 5
      user-service:
        minimum-number-of-calls: 5
feign:
  circuitbreaker:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${EUREKA_HOST:localhost}

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus, health'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
