server:
  port: 8005
spring:
  application:
    name: lists-service
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/lists
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: false
      format_sql: false
    #     open-in-view: false
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false
  flyway:
    locations: classpath:db/migration/lists
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411
  rabbitmq:
    addresses: ${RABBITMQ_HOST:localhost}:5672

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${EUREKA_HOST:localhost}
