server:
  port: 8020
spring:
  application:
    name: topic-service
  datasource:
    url: jdbc:postgresql://localhost:5432/twitter
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: false
      format_sql: false
    #     open-in-view: false
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false
  flyway:
    locations: classpath:db/migration
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
