server:
  port: 8002
spring:
  application:
    name: tweet-service
  datasource:
    url: jdbc:postgresql://localhost:5432/tweet-test
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
google:
  api:
    url: https://www.googleapis.com/youtube/v3/videos?id=%s&key=%s&part=snippet,contentDetails,statistics,status
    key: AIzaSyBtQYzGSmcCzqOztibg1BgSTqv0xwg1D-M
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
