db:
  username: test
  password: test

spring:
  datasource:
    username: test
    password: test
  jpa:
    properties.hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:sql-test/clear-tweet-db.sql, classpath:sql-test/populate-tweet-db.sql
google:
  api:
    url: https://www.googleapis.com/youtube/v3/videos?id=%s&key=%s&part=snippet,contentDetails,statistics,status
    key: AIzaSyBtQYzGSmcCzqOztibg1BgSTqv0xwg1D-M
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
